"""empty message

Revision ID: 4ba35d305804
Revises: 445834d91bc4
Create Date: 2017-03-10 18:34:16.742000

"""

# revision identifiers, used by Alembic.
revision = '4ba35d305804'
down_revision = '445834d91bc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CrawlTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_file', sa.String(), nullable=False),
    sa.Column('m_file', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_file')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CrawlTask')
    ### end Alembic commands ###
